language: go
os:
  - linux
  - osx
go:
  - 1.16.x

install: true

script:
  - go get -u golang.org/x/lint/golint
  - cd $GOPATH/src/github.com/amitsaha/gitbackup/
  - bash ./check_test.bash
  - bash ./build-binaries.bash

deploy:
  provider: releases
  api_key:
    secure: $GITBACKUP_RELEASE
  file_glob: true
  file: artifacts/gitbackup-*
  skip_cleanup: true
  on:
    tags: true
  draft: true
